# Server Configuration
server.port=8082

app.errors.include-details=true

# Application Configuration
spring.application.name=account-service

# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5434/account_db
spring.datasource.username=account_user
spring.datasource.password=account_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Actuator
management.endpoints.web.exposure.include=health,info